apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: timer-log
    app.kubernetes.io/runtime: camel
  name: timer-log
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: timer-log
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timer-log
    spec:
      containers:
      - image: examples/timer-log:1.0.0
        imagePullPolicy: IfNotPresent
        name: timer-log
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
